### ISSUE TITLE
Resolution of type with Func<T> injected corrupts request scoped type lookup

### ISSUE THREAD

**Issue by RandomEngy** [ipjohnson/Grace.MVC#1]
When you make a lookup for a type with Func<T> injected on the constructor, it can mess up the lookup for request-scoped types.

Simple repro on MVC5:
https://drive.google.com/open?id=1StgddYLxUshj0IknbY2zKGo1wc6MUjO3

In this case, the fact that MyMapper is resolved in Global.asax.cs messes up the lookup for IPerRequestThing later on.

**Comment by ipjohnson** [comment]
That is definitely a rather odd bug, I'm going to need a little bit of time to figure it out as nothing pops out to me why it would happen.

**Comment by ipjohnson** [comment]
I'm going to get to this over the next week but my work life, home life, and sleep deprivation have finally caught up to me :)

**Comment by ipjohnson** [comment]
This turned out to be misconfiguration
