### ISSUE TITLE
Instance registered with scope SingletonPerRequest stays for other requests

### ISSUE THREAD

**Issue by RandomEngy** [ipjohnson/Grace.MVC#2]
In example

https://drive.google.com/open?id=1StgddYLxUshj0IknbY2zKGo1wc6MUjO3

If you comment out the crashing line in Global.asax.cs, you still end up getting the same RequestContext object every request, even though it is registered like this on every request:

	Ioc.Container.Configure(b =>
	{
		b.ExportInstance(new RequestContext()).As<IRequestContext>().Lifestyle.SingletonPerRequest();
	});

If you add in a line to print out the hash code for the RequestContext inside PerRequestThing, it always comes up with the same one.

**Comment by ipjohnson** [comment]
@RandomEngy MVC 4&5 don't actually create a new scope for each request (i.e. it doesn't plugin to the owin pipeline) so your code there is actually creating a new registration with the root container for every call (highly recommend not doing that). 

I'm not exactly a big fan of how it's implemented but it was conceived for MVC 4 and as such didn't intend to create a scope for each request.

What's the behavior you are trying to mimic? It would be possible to pass the IRequestContext into the Locate call? Or maybe create a scope for each request in the owin pipeline?

**Comment by RandomEngy** [comment]
Yeah sorry I couldn't find any documentation so I'm trying to just figure out the best thing to call. I'm just trying to get a registration that only visible on that ASP.NET request, and that goes away after the request is complete. Not sure what you mean with the "owin pipeline".

**Comment by ipjohnson** [comment]
Is the app you want to do an MVC 5 application? If so I'll create an example that doesn't use this package but rather a much simpler approach.

The pipeline I was refering to is this [one](https://docs.microsoft.com/en-us/aspnet/aspnet/overview/owin-and-katana/owin-middleware-in-the-iis-integrated-pipeline). If I remember correctly it was introduced in MVC 5 and provides a much cleaner way of doing request scoping.

**Comment by RandomEngy** [comment]
I believe it is MVC5.

**Comment by RandomEngy** [comment]
And yeah, such an example would be a great help!

**Comment by ipjohnson** [comment]
Ok while not pretty this [example](https://drive.google.com/file/d/1NSKxZXjUV97SNvMcz3Rh9q5cKaFwomdI/view) shows you how to use owin to create a scope (lifetime scope vs. child container), controller factory, setting request data into a lifetime scope. 

Here are the things to look at
Startup.cs - create scope
ScopedControllerFactory - create controller as well as sets up per request info
IoC.cs - container setup and extension for accessing dependency in view
_layout.cshtml - added call to dependent service to print per request info

This is a basic example, if you want to do view injection or other more complex things let me know.

**Comment by RandomEngy** [comment]
Thanks! It looks like my team's site isn't on the OWin pipeline, though it's referencing MVC5 DLLs. I'll have to wrangle with it a bit to see if I can get that pipeline running.

**Comment by ipjohnson** [comment]
Ok with that in mind I can do the more complex example that skips owin. It's how I do it at work but it requires a bit more setup for disposal (and it would use this package).

**Comment by ipjohnson** [comment]
Hi @RandomEngy 

I'm sorry this issue ended up falling through the cracks. Were you able to get this worked out or did you just end up moving on?

**Comment by RandomEngy** [comment]
Sorry, I ended up switching to Simple Injector for the project. They have a web scope that works out of the box.

**Comment by ipjohnson** [comment]
No worries then I'll close out your issues.

**Comment by silkfire** [comment]
@ipjohnson I seem to have the same problem. I have a service with lifetime scope `SingletonPerRequest`. It's created when I start the web app but on consecutive requests, it just reuses the same instance.

I'm using ASP.NET Core MVC, am I doing something wrong?

**Comment by ipjohnson** [comment]
This is definitely not the same thing.

Can you open a new issue [here](https://github.com/ipjohnson/Grace.DependencyInjection.Extensions) with an example and I’ll take a look.

**Comment by silkfire** [comment]
@ipjohnson Funny, I actually just tested with a fresh project and it's working fine. But I'm wondering, how do different lifecycles affect a service and its dependencies?

If a service with `Singleton` lifecycle depends on services that are transient, will the main service dependencies be recreated each time and injected into the `Singleton`? Or will the same instance of the service always be returned and the constructor never rerun and repopulated with fresh dependencies?

**Comment by ipjohnson** [comment]
Singletons have one instance and will not be recreated. Otherwise they wouldn’t be a singleton.
